#!/bin/bash

gitdir=$(pwd)
svndir=$(pwd)/../ffmpeg-svn

if [ "$1" == "" ]
then
echo "need commit arguments"
exit 0
fi

cd $svndir
git reset --hard

for x in $(git ls-files | grep -v '\.diff$')
do
diff $svndir/$x $gitdir/$x
cp $gitdir/$x $svndir/$x
done

diffiles=$(git ls-files | grep '\.diff$')

cd $gitdir

for x in $diffiles
do
git diff upstream-local..master -- $(echo $x | sed 's/\.diff$//') > $svndir/$x
done

cd $svndir

for x in $diffiles
do
git diff $x | cat
done

read -p "commit? (y/n) " yesno

if [ "$yesno" != "y" ]
then
exit 0
fi

cd $gitdir
git commit -a -m "$1"
git push origin master

cd $svndir
git commit -a -m "$1"
git svn dcommit

