#!/bin/bash

#trackedfiles="ffmpeg.c libavformat/Makefile libavformat/allformats.c libavformat/concat.c libavformat/concatgen.c libavformat/playlist.c libavformat/playlist.h"

trackedfiles="libavformat/Makefile libavformat/allformats.c libavformat/playlist.c libavformat/playlist.h"

if [ -e ffmpeg-concat.diff ]
then
rm ffmpeg-concat.diff
fi

for x in $trackedfiles
do
git diff upstream-local -- "$x" >> ffmpeg-concat.diff
done

