#!/bin/bash

#trackedfiles="ffmpeg.c libavformat/Makefile libavformat/allformats.c libavformat/concat.c libavformat/concatgen.c libavformat/playlist.c libavformat/playlist.h"

trackedfiles="libavformat/Makefile libavformat/allformats.c libavformat/playlist.c libavformat/playlist.h libavformat/concatgen.c libavformat/concatgen.h libavformat/concat.c libavformat/concat.h libavformat/m3u.c libavformat/pls.c libavformat/xspf.c libavformat/utils.c ffmpeg.c"

if [ -e ffmpeg-concat.diff ]
then
rm ffmpeg-concat.diff
fi

for x in $trackedfiles
do
git diff upstream-local -- "$x" >> ffmpeg-concat.diff
done

